services:
  mysql:
    image: mysql:8.0
    ports:
      - 6606:3306
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-demo

volumes:
  mysql:
