# MySQL
MYSQL_CONFIG:
  host: localhost
  port: 3306
  username: xxx
  password: xxx
  database: plasticine-monitor

# redis
REDIS_CONFIG:
  host: localhost
  port: 6379
  username: default
  password: default
  database: 0
